app:
  version: "0.0.1"
  license: "GNU GPL v3"
  repo: "https://github.com/bxrne/launchrail"
logs:
  file: "launchrail.log"
engine:
  timestep_ns: 10000000 # 10ms
dev:
  orkFile: "testdata/ULR3.ork"

