app:
  name: "launchrail-dev"
  version: "0.0.1"

logging:
  level: "debug"

external:
  openrocket_version: "23.09"

options:
  motor_designation: "269H110-14A"
  openrocket_file: "./testdata/openrocket/l1.ork"
