app:
  name: "launchrail-dev"
  version: "0.0.1"
  base_dir: ".launchrail"

logging:
  level: "debug"

simulation:
  step: 1 # 60hz
  max_time: 300.0

external:
  openrocket_version: "23.09"

options:
  motor_designation: "269H110-14A"
  openrocket_file: "./testdata/openrocket/l1.ork"
  launchrail:
    length: 3.0 
    angle: 2.0
    orientation: 1.0
  launchsite:
    latitude: 37.7749
    longitude: -122.4194
    altitude: 1.0
