name: Run Benchmarks and Update Results

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write # Needed to commit BENCHMARK.md

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Use the Go version your project requires

      - name: Run Simulation to Generate Results
        run: |
          echo "Running simulation to generate benchmark input data..."
          # Simulation writes to setup.app.simulation_output_dir in config.yaml (base benchmarks dir)
          go run ./cmd/launchrail
          echo "Simulation finished. Results should be in the configured benchmarks directory."
          # Verify the benchmarks directories exist
          ls -l "$HOME/.launchrail/benchmarks"

      - name: Run Benchmarks
        id: run_bench # Keep id for potential future status checks
        run: |
          # Run from project root to find config.yaml
          # Configuration is read from config.yaml (no flags needed)
          go run ./cmd/bench/... || true # Ignore exit code for workflow continuation
          echo "Benchmark run finished. Markdown file generation is handled internally based on config."
          # Removed stdout capture and processing logic

      - name: Check if Benchmark File Exists
        id: check_file
        run: |
          # Check if the configured markdown output file exists (using default BENCHMARK.md for now)
          # TODO: Read the actual path from config.yaml if needed for robustness
          if [ -f "BENCHMARK.md" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push BENCHMARK.md
        # Only commit if the file exists (was generated by the benchmark tool)
        if: steps.check_file.outputs.exists == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update benchmark results [skip ci]"
          file_pattern: BENCHMARK.md
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"