name: Run Benchmarks and Update Results

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write # Needed to commit BENCHMARK.md

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Use the Go version your project requires

      - name: Run Simulation to Generate Results
        run: |
          echo "Running simulation to generate benchmark input data..."
          # Simulation writes to setup.app.simulation_output_dir in config.yaml (base benchmarks dir)
          go run ./cmd/launchrail
          echo "Simulation finished. Results should be in the configured benchmarks directory."
          # Verify the benchmarks directories exist
          ls -l "$HOME/.launchrail/benchmarks"

      - name: Run Benchmarks
        id: run_bench # Keep id for potential future status checks
        run: |
          # Run from project root to find config.yaml
          # Configuration is read from config.yaml (no flags needed)
          go run ./cmd/bench/... || true # Ignore exit code for workflow continuation
          echo "Benchmark run finished. Markdown file generation is handled internally based on config."
          # Removed stdout capture and processing logic

      - name: Aggregate Benchmark Results
        id: aggregate_results
        run: |
          BENCHMARK_DIR="$HOME/.launchrail/benchmarks"
          OUTPUT_FILE="BENCHMARK.md"
          echo "# LaunchRail Benchmark Results" > "$OUTPUT_FILE"
          echo "" >> "$OUTPUT_FILE"
          # Find all result.md files and append them, separated by a newline
          find "$BENCHMARK_DIR" -type f -name 'result.md' -exec sh -c 'cat "$1" && echo' _ {} \; >> "$OUTPUT_FILE"
          # Check if any results were actually found and appended beyond the header
          if [ $(wc -l < "$OUTPUT_FILE") -gt 2 ]; then
            echo "results_found=true" >> $GITHUB_OUTPUT
            echo "Aggregated results into $OUTPUT_FILE"
          else
            echo "results_found=false" >> $GITHUB_OUTPUT
            echo "No result.md files found in $BENCHMARK_DIR"
            # Remove the empty/header-only file if no results found
            rm -f "$OUTPUT_FILE"
          fi

      - name: Commit and Push BENCHMARK.md
        # Only commit if results were aggregated
        if: steps.aggregate_results.outputs.results_found == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update benchmark results [skip ci]"
          file_pattern: BENCHMARK.md
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"