name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.19, 1.20]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        make build

    - name: Run tests
      run: |
        make test

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-build
        path: build/

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.out

