name: Docker Build & Publish

permissions:
  contents: write 
  packages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      REPOSITORY: bxrne/launchrail

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set up Python (for commitizen)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install commitizen
        run: pip install commitizen

      - name: Bump version and create tag
        id: cz_bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          set +e
          cz bump --changelog --yes
          if [ $? -ne 0 ]; then
            echo "No commits eligible for bumping. Skipping tag creation."
            exit 0
          fi
          set -e
          TAG=$(cz version --project)
          git tag $TAG
          git push origin $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.cz_bump.outputs.tag }} .
          docker tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.cz_bump.outputs.tag }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

      - name: Push Docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ steps.cz_bump.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
